# -*- coding: utf8 -*-
# ============LICENSE_START=======================================================
# org.onap.vvp/validation-scripts
# ===================================================================
# Copyright © 2020 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the "License");
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the "License");
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
onap_client:
  sdc:
    SDC_BE_ENDPOINT: https://sdc.api.be.simpledemo.onap.org:30204
    SDC_FE_ENDPOINT: https://sdc.api.be.simpledemo.onap.org:30207
    SDC_HC_ENDPOINT: https://sdc.api.be.simpledemo.onap.org:30207
    SDC_BE_ONBOARD_ENDPOINT: https://sdc.api.be.simpledemo.onap.org:31360
    SDC_CONSUMER_USERNAME: vid
    SDC_CONSUMER_PASSWORD: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
    SDC_DESIGNER_USER_ID: cs0008
    SDC_TESTER_USER_ID: jm0007
    SDC_OPS_USER_ID: op0001
    SDC_GOVERNOR_USER_ID: gv0001
    SDC_DESIGNER_PASSWORD: demo123456!
    GLOBAL_SDC_USERNAME: beep
    GLOBAL_SDC_PASSWORD: boop
    SDC_CONSUMER_CATALOG_PATH: /sdc/v1/catalog
    SDC_SCREEN_PATH: /sdc2/rest/v1/screen
    SDC_HEALTH_CHECK_PATH: /sdc1/rest/healthCheck
    SDC_CATALOG_SERVICES_PATH: /sdc2/rest/v1/catalog/services
    SDC_VENDOR_SOFTWARE_PRODUCT_PATH: /onboarding-api/v1.0/vendor-software-products
    SDC_CATALOG_RESOURCES_PATH: /sdc2/rest/v1/catalog/resources
    SDC_VENDOR_LICENSE_MODEL_PATH: /onboarding-api/v1.0/vendor-license-models
    SDC_VENDOR_ITEMS_PATH: /onboarding-api/v1.0/items
    SDC_FE_CATALOG_RESOURCES_PATH: /sdc1/feProxy/rest/v1/catalog/resources
    ABSTRACT_NODE_PREFIX: abstract_
    POLICIES:
      SCALING_FIXED: org.openecomp.policies.scaling.Fixed
      EXTERNAL: org.openecomp.policies.External
      PLACEMENT: tosca.policies.Placement
    GROUPS:
      NETWORK_COLLECTION: org.openecomp.groups.NetworkCollection
      PLACEMENT_GROUP: tosca.groups.nfv.PlacementGroup
      VFC_INSTANCE: org.openecomp.groups.VfcInstanceGroup
    SERVICE_DISTRIBUTION:
      - "request_service_certification"
      - "start_service_certification"
      - "finish_service_certification"
      - "approve_service_certification"
    POLL_INTERVAL: 30
  aai:
    AAI_BE_ENDPOINT: https://aai.api.simpledemo.onap.org:30233
    AAI_BUSINESS_PATH: /aai/v16/business
    AAI_CLOUD_INFRASTRUCTURE_PATH: /aai/v16/cloud-infrastructure
    AAI_HEALTH_CHECK_PATH: /aai/util/echo
    AAI_USERNAME: AAI
    AAI_PASSWORD: AAI
  sdnc:
    SDNC_ENDPOINT: http://sdnc.api.simpledemo.onap.org:30267
    SDNC_OPERATIONS_PATH: /restconf/operations
    SDNC_CONFIG_PATH: /restconf/config
    SDNC_USERNAME: admin
    SDNC_PASSWORD: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
  vid:
    VID_ENDPOINT: http://vid.api.simpledemo.onap.org:30238
    VID_MAINTENANCE_PATH: /vid/maintenance
    VID_HEALTH_CHECK_PATH: /vid/healthCheck
  so:
    SO_ENDPOINT: http://sdc.so.be.simpledemo.onap.org:30277
    SO_HEALTH_CHECK_PATH: /globalhealthcheck
    SO_USERNAME: bpel
    SO_PASSWORD: password1$
    SO_SERVICE_INSTANCE_PATH: /onap/so/infra/serviceInstantiation/v7/serviceInstances
    SO_ORCHESTRATION_PATH: /onap/so/infra/orchestrationRequests/v7/
  LOG_LEVEL: DEBUG
